export const GET_ALL_EMPLOYEE = "GET_ALL_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const CLEAR_EMPLOYEE = "CLEAR_EMPLOYEE";
